### PR TITLE
Allow specifying Docker build platforms

### PR DESCRIPTION
**Pull request by sorenisanerd**
I think a default of `linux/amd64,linux/arm64` would be fantastic, but didn't know if that would too opinionated for this tool.

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
> but didn't know if that would too opinionated for this tool.

It is opinionated front to back and every piece in the middle, so that shouldn't be a problem.

For go binaries the maintenance overhead should be ignoreable especially since we have next to 0 dependencies here.

If our internal tooling has problems with this, it will be a good excerise to make things more robust but I don't think that things will break.

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by majewsky** [comment]
Aaah, Sandro, I just wanted to reject this. I don't want even more options. Just put amd64+arm64 as the only option.

**Comment by majewsky** [comment]
https://github.com/sapcc/go-makefile-maker/commit/96e5071c10b0370163f68dccf11e1c90ef265b7d

**Comment by SuperSandro2000** [comment]
I think we should have an option to turn this off other than turning of the CI generation. Arm64 builds can fail for stupid reasons (cgo being the most prominent) and I or others shouldn't have the worry about this especially if we want all go things to use this.

But let's talk about this later in private.

**Pull request merged**
