### PR TITLE
Allow having no binaries which logs an INFO and disables build steps

### PR DESCRIPTION
**Pull request by SuperSandro2000**

### CODE REVIEW

**Comment by majewsky** [comment]
Counterproposal:

- Having no binaries is just an accepted state and does not log anything.
- When there are no binaries, `make default` is a no-op that prints an informational message along the lines of "there is nothing to build, use make check for running the tests".

**Review by majewsky — CHANGES_REQUESTED** [review]
Without binaries, the Makefile will generate an invalid `check` target:
```
$ make check
make: *** No rule to make target 'build-all', needed by 'check'.  Stop.
```

**Comment by SuperSandro2000** [comment]
Removed the log and fixed the check target.

**Comment by majewsky** [comment]
Now the `check` target gets generated without a dependency on `build/cover.html`, which causes `make check` to skip the unit tests. Also, `make build/cover.html` prints some unsightly warnings:

```
Makefile:38: warning: undefined variable 'GO_TESTENV'
Makefile:38: warning: undefined variable 'GO_BUILDFLAGS'
Makefile:38: warning: undefined variable 'GO_LDFLAGS'
```

Since these variables are also used by `go test`, they should still be defined even without binaries.

**Comment by SuperSandro2000** [comment]
Now it should be right

**Pull request merged**
